export enum IntermediateKind
{
    File = 'File',
    // Declarations:
    Function = 'Function',
    Constant = 'Constant',
    External = 'External',
    // Statements:
    Add = 'Add',
    And = 'And',
    Call = 'Call',
    Compare = 'Compare',
    Dismiss = 'Dismiss',
    Divide = 'Divide',
    Give = 'Give',
    Global = 'Global',
    Goto = 'Goto',
    Introduce = 'Introduce',
    JumpIfEqual = 'JumpIfEqual',
    JumpIfGreater = 'JumpIfGreater',
    JumpIfLess = 'JumpIfLess',
    JumpIfNotEqual = 'JumpIfNotEqual',
    Label = 'Label',
    Move = 'Move',
    Modulo = 'Modulo',
    Multiply = 'Multiply',
    Negate = 'Negate',
    Not = 'Not',
    Or = 'Or',
    Return = 'Return',
    Subtract = 'Subtract',
    Take = 'Take',
}
