export enum SyntaxKind
{
    File = 'File',
    Section = 'Section',
    Namespace = 'Namespace',
    Module = 'Module',
    Import = 'Import',
    FunctionDeclaration = 'FunctionDeclaration',
    FunctionParameter = 'FunctionParameter',
    Type = 'Type',
    TypeClause = 'TypeClause',
    ElseClause = 'ElseClause',
    // Statements
    Assignment = 'Assignment',
    LocalVariableDeclaration = 'LocalVariableDeclaration',
    GlobalVariableDeclaration = 'GlobalVariableDeclaration',
    FieldVariableDeclaration = 'FieldVariableDeclaration',
    ReturnStatement = 'ReturnStatement',
    IfStatement = 'IfStatement',
    WhileStatement = 'WhileStatement',
    // Expressions
    AccessExpression = 'AccessExpression',
    UnaryExpression = 'UnaryExpression',
    BinaryExpression = 'BinaryExpression',
    BracketedExpression = 'BracketedExpression',
    LiteralExpression = 'LiteralExpression',
    IdentifierExpression = 'IdentifierExpression',
    CallExpression = 'CallExpression',
    InstantiationExpression = 'InstantiationExpression',
}
