export enum TokenKind
{
    NoToken,
    // Tokens
    IdentifierToken,
    IntegerToken,
    StringToken,
    OpeningParenthesisToken,
    ClosingParenthesisToken,
    OpeningCurlyBraceToken,
    ClosingCurlyBraceToken,
    OpeningSquareBracketToken,
    ClosingSquareBracketToken,
    DotToken,
    ColonToken,
    SemicolonToken,
    CommaToken,
    LineCommentToken,
    BlockCommentToken,
    // Operators
    AssignmentOperator,
    PlusOperator,
    MinusOperator,
    StarOperator,
    SlashOperator,
    PercentOperator,
    EqualOperator,
    NotEqualOperator,
    LessOperator,
    GreaterOperator,
    NotOperator,
    AndOperator,
    OrOperator,
    // Keywords
    ModuleKeyword,
    VarKeyword,
    FunctionKeyword,
    ReturnKeyword,
    HeaderKeyword,
    IfKeyword,
    ElseKeyword,
    WhileKeyword,
    TrueKeyword,
    FalseKeyword,
    ImportKeyword,
}
